# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfoo.proto\"\x95\x02\n\x03Rom\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.Rom.RomType\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x19\n\x11manufacturer_name\x18\x03 \x01(\t\x12\x0f\n\x07voltage\x18\x04 \x01(\r\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x0f\n\x07write_1\x18\x06 \x01(\x08\x12\x0f\n\x07write_2\x18\x07 \x01(\x05\x12\x17\n\x0fmanufacturer_id\x18\x08 \x01(\r\x12\x11\n\tdevice_id\x18\t \x01(\r\x12\x10\n\x08\x65\x65\x39\x33_unk\x18\n \x01(\r\x12\x11\n\tee93_bits\x18\x0b \x01(\r\"0\n\x07RomType\x12\x07\n\x03Spi\x10\x00\x12\x08\n\x04\x45\x45\x32\x34\x10\x01\x12\x08\n\x04\x45\x45\x32\x35\x10\x02\x12\x08\n\x04\x45\x45\x39\x33\x10\x03\"\x1a\n\x04Roms\x12\x12\n\x04roms\x18\x01 \x03(\x0b\x32\x04.Romb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROM._serialized_start=14
  _ROM._serialized_end=291
  _ROM_ROMTYPE._serialized_start=243
  _ROM_ROMTYPE._serialized_end=291
  _ROMS._serialized_start=293
  _ROMS._serialized_end=319
# @@protoc_insertion_point(module_scope)
